### ISSUE TITLE
 Code Runner 插件配置少一关键参数，如下

### ISSUE THREAD

**Issue by mapleriver** [spencerwoo98/Dev-on-Windows-with-WSL#1]
"code-runner.terminalRoot": "/mnt/"

**Comment by spencerwoo98** [comment]
我在这里做了一些更改，看一下 [这个链接](https://spencerwoo.com/Dev-on-Windows-with-WSL/3-VSCode/3-3-C_Cpp.html#%E5%9C%A8-visual-studio-code-%E4%B8%AD%E5%AE%89%E8%A3%85%E4%B8%80%E4%BA%9B%E6%8F%92%E4%BB%B6)。

我这样表述没问题吧？
![](https://user-images.githubusercontent.com/32114380/47255505-d6e72e00-d4a4-11e8-9779-57597a420680.png)

**Comment by jiangbianyiye** [comment]
没有问题

**Comment by jiangbianyiye** [comment]
你修改过"code-runner.executorMap"参数吗？ 默认是不会将windows的盘符路径替换掉啊

**Comment by spencerwoo98** [comment]
改了 C/C++ 的，但是没改 Python 的。不过 Python 确实路径正常，我刚刚特意试了一下。

PS：感觉 code-runner 是个挺重要的插件，明天我把这个单独分一个页面写吧，各种语言基本都能用它来编译运行。然后再看看 code-runner 到底怎么判定这个路径的。感谢您的建议！👏👏👏

**Comment by jiangbianyiye** [comment]
我刚才测试了一下，我这边去掉/mnt/后，跑python路径也是不正确的。很期待你明天的工作成果

**Comment by spencerwoo98** [comment]
新增了一个页面，单独介绍 Code Runner，在 [这里](https://spencerwoo.com/Dev-on-Windows-with-WSL/3-VSCode/3-2-Code-Runner.html)。

今天详细看了一下 Code Runnner 下面的 Issue，[有关 WSL 的里面](https://github.com/formulahendry/vscode-code-runner/issues?utf8=%E2%9C%93&q=wsl+)确实有几个重点说明了这个路径问题。[Issue #106](https://github.com/formulahendry/vscode-code-runner/issues/106) 解决了这个问题，就是如果让 Code Runner 在集成终端中运行，集成终端默认用的是 Bash on Windows，那么 Code Runner 会自动将路径切换至 Linux 路径。

> @garytyler Did you set WSL for the VS Code terminal? If yes, the Code Runner would automatically change the file path. Refer to #106

这里的 `code-runner.terminalRoot` 看来是为了重点解决使用 WSL 和使用 Git Bash 的用户的路径冲突问题（根目录路径一个是 `/mnt/c`，一个是 `/c`）。无论如何，这里设置一下还是有益无害的，确保正常运行。感谢建议！👏👏👏

没什么问题的话我就把这个 Issue 关掉了~

**Comment by mapleriver** [comment]
原来这样，谢谢告知，issue可以关了

**Comment by Tracker647** [comment]
> 我在这里做了一些更改，看一下 [这个链接](https://spencerwoo.com/Dev-on-Windows-with-WSL/3-VSCode/3-3-C_Cpp.html#%E5%9C%A8-visual-studio-code-%E4%B8%AD%E5%AE%89%E8%A3%85%E4%B8%80%E4%BA%9B%E6%8F%92%E4%BB%B6)。
> 
> 我这样表述没问题吧？ ![](https://user-images.githubusercontent.com/32114380/47255505-d6e72e00-d4a4-11e8-9779-57597a420680.png)

修改root路径确实能解决问题，但如果我要修改回powershell的话怎么办呢，最好有个方法能够根据终端不同动态修改路径。
